# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@5.0.2

publish: &publish
  working_directory: ~/FunFitFE
  docker:
    - image: circleci/node:12.13.0
  steps:
    - checkout
    # - restore_cache:
    #     name: Restore yarn package cache
    #     key: v1-cache-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}-{{ arch }}
    - run:
        name: Install dependencies
        command: npm ci
    # - save_cache:
    #     name: Save yarn package cache
    #     paths:
    #       - ~/.cache/yarn
    #     key: v1-cache-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}-{{ arch }}
    - run:
        name: Login into Expo
        command: npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
    - run:
        name: Save current branch name to an env variable
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            echo 'export EXPO_RELEASE_CHANNEL="default"' >> $BASH_ENV
          else
            echo 'export EXPO_RELEASE_CHANNEL=$CIRCLE_BRANCH' >> $BASH_ENV
          fi
    - run:
        name: Publish to Expo
        command: npx expo publish --non-interactive --max-workers 1 --release-channel $EXPO_RELEASE_CHANNEL

jobs:
  build_and_test:
    docker:
      - image: circleci/node:12.13.0
    steps:
      - checkout
      # - restore_cache:
      #     name: Restore yarn package cache
      #     key: v1-cache-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}-{{ arch }}
      - run:
          name: Install dependencies
          command: npm install --force
      # - save_cache:
      #     name: Save yarn package cache
      #     paths:
      #       - ~/.cache/yarn
      #     key: v1-cache-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}-{{ arch }}
      - run:
          name: Run tests
          command: npm test

  publish_to_expo:
    environment:
      EXPO_RELEASE_CHANNEL: dev
    <<: *publish

workflows:
  version: 2
  FunFitFE: 
    jobs:
      - build_and_test
      - publish_to_expo:
          requires: 
            - build_and_test
          filters:
            branches:
              ignore: gh-pages
