export const loginURL = "https://orbital-funfit.herokuapp.com/user/login";
export const signupURL = "https://orbital-funfit.herokuapp.com/user/signup";
export const userURL = "https://orbital-funfit.herokuapp.com/user/me";
export const resetpwdURL = "https://orbital-funfit.herokuapp.com/user/resetPassword";
export const forgotURL = "https://orbital-funfit.herokuapp.com/user/forgotPassword";
export const getRecURL = "https://orbital-funfit.herokuapp.com/routine/getRecRoutines";
export const updateProfileURL = "https://orbital-funfit.herokuapp.com/user/updateProfile";
export const addRoutineURL = "https://orbital-funfit.herokuapp.com/routine/newRoutine";
export const getMyURL = "https://orbital-funfit.herokuapp.com/routine/getMyRoutines";
export const deleteRoutineURL = "https://orbital-funfit.herokuapp.com/routine/deleteRoutine";
export const editRoutineURL = "https://orbital-funfit.herokuapp.com/routine/editRoutine";
export const uploadImageURL = "https://orbital-funfit.herokuapp.com/user/upload";
export const downloadPicURL = "https://orbital-funfit.herokuapp.com/user/downloadPic";

//export default axios.create({baseURL: "https://orbital-funfit.herokuapp.com"});
// export const loginURL = "https://secret-garden-61740.herokuapp.com/https://orbital-funfit.herokuapp.com/user/login";
// export const signupURL = "https://secret-garden-61740.herokuapp.com/https://orbital-funfit.herokuapp.com/user/signup";
// export const userURL = "https://secret-garden-61740.herokuapp.com/https://orbital-funfit.herokuapp.com/user/me";
// export const forgotURL = "https://secret-garden-61740.herokuapp.com/https://orbital-funfit.herokuapp.com/user/forgotPassword";
//export const resetpwdURL = "https://secret-garden-61740.herokuapp.com/https://orbital-funfit.herokuapp.com/user/resetPassword";
